### PR TITLE
Add android support and fix up some windows support

### PR DESCRIPTION
**Pull request by dllewellyn**
* Changed some of the build configs so that only, e.g. mac binaries execute mac executables etc
* Added windows support
* Added android support

Test on MacOS (latest)
Windows 10
Android (5.1.1)

Neither tests, nor exe tested on any of the linux OSs yet

### CODE REVIEW

**Comment by colindean** [comment]
@schultyy Is the approach in this still valid? @natboehm and I are looking into cleaning up this PR so it can be merged, as we are in need of Windows support.

**Comment by luciusmagn** [comment]
I am also interested in using this

**Comment by schultyy** [comment]
@colindean Hey! I'm sorry for the long delay here. I've looked through the Pull Request again and the general approach is definitely valid. To keep the changesets manageable what about you submitting a PR per platform? :)

**Comment by DannyPeck** [comment]
I would be very interested in using this functionality, is there a reason this hasn't been merged?

**Comment by schultyy** [comment]
Closing due to inactivity.  Also commit messages don't follow conventions.

**Pull request closed without merging**
