### PR TITLE
Add Deepin Linux Support

### PR DESCRIPTION
**Pull request by alexsunxl**
## What does this do?
add a os type `Deepin` support

---

Hello. I used this rust lib in my linux laptop， but it's failed for get `unknow`。
I add a support and unit test.

### CODE REVIEW

**Comment by alexsunxl** [comment]
@schultyy hello. could you merge this

**Comment by schultyy** [comment]
@alexsunxl thanks for the ping! LGTM and merging now

**Comment by schultyy** [comment]
@alexsunxl Please update to version `2.4.0`.

**Comment by alexsunxl** [comment]
OK

**Pull request merged**
